### ISSUE TITLE
Provide support for testing of quiescent-consistency

### ISSUE THREAD

**Issue by elizarov** [Devexperts/lin-check#5]
Some useful data structures, like fast MPSC queues that are used for scheduling, are not linearizable, but give weaker guarantees like _quiescent consistency_ in particular. It seems straightforward to extend lin-check methodology to support testing for quiescent consistency, too. 

Note, that the existing framework for custom verifiers is not flexible enough to support that. It only support pluggable verification stage, while testing for quiescent consistency requires run a larger set of transpositions on original operation (all of the shall be tested without regard for program order).

**Comment by ndkoval** [comment]
Quiescent consistency verifier will be added in the next version.
