### ISSUE TITLE
How to check not linearizable data structure ? 

### ISSUE THREAD

**Issue by martynovig** [Devexperts/lin-check#6]
`@StressCTest(iterations = 300, actorsPerThread = {"1:3", "1:3", "1:3"})
@Param(name = "value", gen = IntGen.class)
public class LinkedList1 {

    private List<Integer> list;

    @Reset
    public void reset() {
        list = new LinkedList<>();
    }

    @Operation(params = {"value"})
    public void add(Integer value) {
        list.add(value);
    }

    @Operation(params = {"value"})
    public void remove(Integer value) {
        list.remove(value);
    }

    @Test
    public void test() {
        LinChecker.check(LinkedList1.class);
    }
}`

This test is always true for Array & Linked list, it is okay, because they are not concurrent ?
Can you provide incorrect list or test for that ?

**Comment by ndkoval** [comment]
What does "it is always true" mean?

As for correct and incorrect examples, you can find them in 'libtest' module.

**Comment by martynovig** [comment]
@ndkoval Thank you for answer, i found mistake
