### ISSUE TITLE
Parametrization of tests

### ISSUE THREAD

**Issue by elizarov** [Devexperts/lin-check#9]
Currently, the way runner is invoker via classname does not let itself easily to parametrization. Consider a datastructure with two modes of operation and we want to run lin-check with it without copy-and-paste:

```
class XxxTest(val mode: Boolean) {
    lateinit var ds: DataStructure

    @Reset { ds = DataStructure(mode) }

    // operations here

    @Test fun test() {
        val optinos = ... 
        LinChecker.check(XxxTest::class.java, options)
    }
}
```

This above code does not work, because there is not default constructor in `XxxTest`. If you extract common parts into a base class and make two inherited classes for each mode, then it does not work either, because lincheck cannot find `@Reset` method declared in a parent. 

Some supported way of running parametrized tests is needed.

**Comment by ndkoval** [comment]
You just need to split the logic into 2 classes. The first one describes a concurrent test and does not run anything. The second class is your parameterized test, which stores the parameters into static fields (to use them by the concurrent test) and runs this concurrent test as usual.

Please, look at this example:
https://github.com/Devexperts/lin-check/blob/master/libtest/src/test/java/com/devexperts/dxlab/lincheck/tests/custom/transfer/AccountsTest.java

Does this solve your problem?
